% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Mar-2021 13:25:42
%  MATLAB version: 9.9.0.1570001 (R2020b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('timeStamps.mat');

dur = saveVarsMat.dur; % <1x1 duration> unsupported class

clear saveVarsMat;
